sudo: required

dist: bionic

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

language: java

jdk:
  - oraclejdk11

env:
  global:
    - DEFOLD_BOOSTRAP_COLLECTION=/test/test.collectionc

script:
  - "./.travis/run.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash)
